version: "3.7"
services:
  mandu-nginx-service:
    build:
      context: ./config
      dockerfile: Dockerfile
    volumes:
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./source:/var/www/html"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - mandu-php-service
      - mandu-mysql-service
    links:
      - mandu-php-service
  mandu-php-service:
    image: php:8.0-fpm
    container_name: mandu-php-service
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "./source:/var/www/html"
    depends_on:
      - mandu-mysql-service
    environment:
      PMA_HOST: mandu-mysql-service
      PMA_USERE: mandu
      PMA_PASSWORD: mandu
  mandu-mysql-service:
    image: mysql
    platform: linux/x86_64
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mandu_db
      - MYSQL_USER=mandu
      - MYSQL_PASSWORD=mandu
    ports:
      - "3306:3306"

  mandu-phpmyadmin-service:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mandu-mysql-service
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    depends_on:
      - mandu-mysql-service